### ISSUE TITLE
Refactoring the code ?

### ISSUE THREAD

**Issue by CyrilRoelandteNovance** [haypo/sixer#2]
Hey !

So, sixer is pretty cool already, but after looking at the code, I have some suggestions.

First of all, the CLI is not especially user-friendly: one would expect a "--help" option that would list checkers and give a detailed, noobie-oriented description of what they do, for instance.

Secondly, I do not think one can use sixer with a "plugin" that would fit their very specific needs and that would not be suitable for upstream. It would be nice to be able to define a checker/fixer as a plugin, or to load it as a module.

Finally, the code is getting quite big and a bit hard to read, imho. I would much rather define a Fixer/Checker class per task (so, an "IteritemsFixer" class, a "RangeFixer" class, etc.) that would have a "check()" and a "patch()" method, as well as a string giving detailed explanations about what it does. We would have all the code related to a change at the same place and could probably use some OOP magic to factorize some code.

WDYT ?

**Comment by vstinner** [comment]
Yeah, I know that the code sucks. It's a quick & dirty project which answers to a very specific use case. I accept patches to enhance the code ;-)

**Comment by vstinner** [comment]
Fixed by commit 8c897fcf50805ffc954f6e4ffaaffcd02923f81d.
